########################################################################################################################
### 공통
########################################################################################################################
spring:
  profiles:
    active: local


application:
  title: hello application

logging:
  config: classpath:logback-spring.xml


---

########################################################################################################################
### LOCAL
########################################################################################################################
spring:
  config:
    activate:
      on-profile: local

server:
  port: 7777


---

########################################################################################################################
### DEV
########################################################################################################################
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8888


---

########################################################################################################################
### QA
########################################################################################################################
spring:
  config:
    activate:
      on-profile: qa

server:
  port: 8080


---

########################################################################################################################
### 운영
########################################################################################################################
spring:
  config:
    activate:
      on-profile: prod