########################################################################################################################
### 공통
########################################################################################################################
spring:
  profiles:
    active: local

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  messages:
    basename: i18n/exception
    encoding: UTF-8

application:
  title: hello application

logging:
  config: classpath:logback-spring.xml


---

########################################################################################################################
### LOCAL
########################################################################################################################
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

server:
  port: 8080


---

########################################################################################################################
### DEV
########################################################################################################################
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8888


---

########################################################################################################################
### QA
########################################################################################################################
spring:
  config:
    activate:
      on-profile: qa

server:
  port: 8080


---

########################################################################################################################
### 운영
########################################################################################################################
spring:
  config:
    activate:
      on-profile: prod